//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSolution.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreSchemaMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreSchemaMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonSolution.Domain.Resources.CoreSchemaMessage", typeof(CoreSchemaMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Física..
        /// </summary>
        public static string CSM0001 {
            get {
                return ResourceManager.GetString("CSM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Jurídica..
        /// </summary>
        public static string CSM0002 {
            get {
                return ResourceManager.GetString("CSM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa Estrangeira..
        /// </summary>
        public static string CSM0003 {
            get {
                return ResourceManager.GetString("CSM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado..
        /// </summary>
        public static string CSM0004 {
            get {
                return ResourceManager.GetString("CSM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo..
        /// </summary>
        public static string CSM0005 {
            get {
                return ResourceManager.GetString("CSM0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspenso..
        /// </summary>
        public static string CSM0006 {
            get {
                return ResourceManager.GetString("CSM0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado..
        /// </summary>
        public static string CSM0007 {
            get {
                return ResourceManager.GetString("CSM0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoProduto..
        /// </summary>
        public static string CSM0008 {
            get {
                return ResourceManager.GetString("CSM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto Físico..
        /// </summary>
        public static string CSM0009 {
            get {
                return ResourceManager.GetString("CSM0009", resourceCulture);
            }
        }
    }
}
