//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSolution.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonSolution.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseException - Erro no banco de dados: {0}.
        /// </summary>
        public static string DatabaseException {
            get {
                return ResourceManager.GetString("DatabaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar a entidade {0} com id {1}..
        /// </summary>
        public static string DeleteEntityError {
            get {
                return ResourceManager.GetString("DeleteEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um registro com {0} igual a {1}..
        /// </summary>
        public static string DuplicateEntry {
            get {
                return ResourceManager.GetString("DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade {0} com identificador {1} não foi encontrada..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXC0001 - Company não localizada..
        /// </summary>
        public static string EXC0001 {
            get {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao comunicar com serviço externo {0}. Mensagem: {1}.
        /// </summary>
        public static string ExternalServiceError {
            get {
                return ResourceManager.GetString("ExternalServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço externo {0} está indisponível no momento..
        /// </summary>
        public static string ExternalServiceUnavailable {
            get {
                return ResourceManager.GetString("ExternalServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationException - Erro de validação dos campos informados..
        /// </summary>
        public static string FluentValidationException {
            get {
                return ResourceManager.GetString("FluentValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As credenciais fornecidas são inválidas..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor {0} não é válido para o campo {1}..
        /// </summary>
        public static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} está em um formato inválido..
        /// </summary>
        public static string InvalidFieldFormat {
            get {
                return ResourceManager.GetString("InvalidFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O payload recebido não é um JSON válido..
        /// </summary>
        public static string InvalidJsonPayload {
            get {
                return ResourceManager.GetString("InvalidJsonPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A assinatura do webhook recebido é inválida..
        /// </summary>
        public static string InvalidWebhookSignature {
            get {
                return ResourceManager.GetString("InvalidWebhookSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo obrigatório {0} está ausente ou nulo..
        /// </summary>
        public static string RequiredFieldMissing {
            get {
                return ResourceManager.GetString("RequiredFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar a entidade {0}. Detalhes: {1}.
        /// </summary>
        public static string SaveEntityError {
            get {
                return ResourceManager.GetString("SaveEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado ao recurso requisitado..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado. Por favor, tente novamente..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar a entidade {0} com id {1}..
        /// </summary>
        public static string UpdateEntityError {
            get {
                return ResourceManager.GetString("UpdateEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário com identificador {0} não foi encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
