//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSolution.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonSolution.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiMethod.
        /// </summary>
        public static string ECM0000 {
            get {
                return ResourceManager.GetString("ECM0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTeam.
        /// </summary>
        public static string ECM0001 {
            get {
                return ResourceManager.GetString("ECM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkerProcess.
        /// </summary>
        public static string ECM0002 {
            get {
                return ResourceManager.GetString("ECM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalIntegration.
        /// </summary>
        public static string ECM0003 {
            get {
                return ResourceManager.GetString("ECM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduledTask .
        /// </summary>
        public static string ECM0004 {
            get {
                return ResourceManager.GetString("ECM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        public static string ECM0005 {
            get {
                return ResourceManager.GetString("ECM0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token.
        /// </summary>
        public static string ECM0006 {
            get {
                return ResourceManager.GetString("ECM0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Token.
        /// </summary>
        public static string ECM0007 {
            get {
                return ResourceManager.GetString("ECM0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Token.
        /// </summary>
        public static string ECM0008 {
            get {
                return ResourceManager.GetString("ECM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoked Token.
        /// </summary>
        public static string ECM0009 {
            get {
                return ResourceManager.GetString("ECM0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Token.
        /// </summary>
        public static string ECM0010 {
            get {
                return ResourceManager.GetString("ECM0010", resourceCulture);
            }
        }
    }
}
